const medicineData = {
    "cold": "Paracetamol",
    "cough": "Dextromethorphan",
    "fever": "Paracetamol",
    "headache": "Ibuprofen",
    "migraine": "Sumatriptan",
    "sore throat": "Azithromycin",
    "tonsillitis": "Amoxicillin",
    "sinusitis": "Amoxicillin-Clavulanate",
    "pneumonia": "Azithromycin",
    "bronchitis": "Amoxicillin",
    "asthma": "Salbutamol",
    "allergy": "Cetirizine",
    "skin allergy": "Levocetirizine",
    "itching": "Hydroxyzine",
    "sneezing": "Cetirizine",
    "runny nose": "Chlorpheniramine",
    "blocked nose": "Oxymetazoline nasal spray",
    "nasal congestion": "Xylometazoline nasal spray",
    "flu": "Oseltamivir",
    "body ache": "Paracetamol",
    "joint pain": "Diclofenac",
    "back pain": "Aceclofenac",
    "muscle pain": "Ibuprofen",
    "shoulder pain": "Diclofenac",
    "neck pain": "Aceclofenac",
    "stiff neck": "Thiocolchicoside",
    "toothache": "Ketorolac",
    "gum infection": "Metronidazole",
    "mouth ulcer": "Chlorhexidine mouth gel",
    "sore gums": "Benzydamine mouth rinse",
    "eye infection": "Moxifloxacin eye drops",
    "red eyes": "Naphazoline eye drops",
    "dry eyes": "Carboxymethylcellulose eye drops",
    "ear pain": "Ofloxacin ear drops",
    "ear infection": "Ciprofloxacin ear drops",
    "throat infection": "Azithromycin",
    "urinary tract infection": "Ciprofloxacin",
    "burning urination": "Nitrofurantoin",
    "acidity": "Omeprazole",
    "heartburn": "Pantoprazole",
    "gas": "Simethicone",
    "indigestion": "Domperidone",
    "nausea": "Ondansetron",
    "vomiting": "Ondansetron",
    "bloating": "Simethicone",
    "constipation": "Lactulose",
    "diarrhea": "ORS",
    "loose motion": "Loperamide",
    "stomach pain": "Dicyclomine",
    "abdominal cramps": "Mebeverine",
    "acid reflux": "Rabeprazole",
    "food poisoning": "Ciprofloxacin",
    "appendicitis": "Ceftriaxone",
    "typhoid": "Cefixime",
    "malaria": "Artemether-Lumefantrine",
    "dengue": "Paracetamol",
    "cholera": "ORS",
    "dehydration": "ORS",
    "heat stroke": "Paracetamol",
    "sunstroke": "ORS",
    "anemia": "Ferrous sulfate",
    "vitamin deficiency": "Multivitamin",
    "calcium deficiency": "Calcium carbonate + Vitamin D3",
    "iron deficiency": "Ferrous ascorbate",
    "vitamin D deficiency": "Cholecalciferol",
    "hair fall": "Biotin",
    "dandruff": "Ketoconazole shampoo",
    "acne": "Clindamycin gel",
    "pimples": "Adapalene gel",
    "skin infection": "Mupirocin",
    "fungal infection": "Clotrimazole",
    "ringworm": "Terbinafine",
    "eczema": "Hydrocortisone cream",
    "psoriasis": "Calcipotriol",
    "itchy scalp": "Ketoconazole shampoo",
    "boils": "Amoxicillin",
    "burn wound": "Silver sulfadiazine cream",
    "cuts": "Povidone-iodine",
    "insect bite": "Calamine lotion",
    "mosquito bite": "Calamine lotion",
    "diabetes": "Metformin",
    "high blood pressure": "Amlodipine",
    "low blood pressure": "ORS",
    "cholesterol": "Atorvastatin",
    "thyroid": "Levothyroxine",
    "obesity": "Orlistat",
    "insomnia": "Zolpidem",
    "anxiety": "Alprazolam",
    "depression": "Fluoxetine",
    "stress": "Escitalopram",
    "panic attack": "Clonazepam",
    "motion sickness": "Dimenhydrinate",
    "period pain": "Mefenamic acid",
    "irregular periods": "Medroxyprogesterone",
    "pms": "Evening primrose oil",
    "menopause": "Hormone replacement therapy",
    "pregnancy nausea": "Doxylamine + Pyridoxine",
    "cold and cough": "Paracetamol + Dextromethorphan + Phenylephrine",
    "covid": "Paracetamol + Zinc + Vitamin C",
    "immune weakness": "Vitamin C",
    "fatigue": "Vitamin B complex",
    "weakness": "Multivitamin",
    "loss of appetite": "Cyproheptadine",
    "motion sickness": "Meclizine"
}

export default medicineData;